### ISSUE TITLE
Add proper error page for authentication

### ISSUE THREAD

**Issue by Hari-Kumar-A** [Hari-Kumar-A/Student-Organiser#5]
- Currently, when wrong email or password is set, it sends a normal message like this below.
<img width="274" alt="image" src="https://github.com/Hari-Kumar-A/Student-Organiser/assets/125040587/80720448-c62b-46fc-8111-7a497e056ce7">

- Add a alert message or warning for invalid credentials

**Comment by adey-github** [comment]
please assign this issue to me.
